# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:55
from __future__ import unicode_literals

import Test.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='important',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[Test.validators.validate_important]),
        ),
    ]
