# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Наименование категории')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Категория подтверждена')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
                'permissions': (('confirm_category', 'Can confirm_category'),),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_based_on_scale', models.IntegerField(verbose_name='Оценка по шкале')),
                ('passing_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата прохождения теста')),
                ('correct_answers_percentage', models.IntegerField(verbose_name='Процент правильных ответов в целочисленном формате')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, к которому относится результат прохождения')),
            ],
            options={
                'verbose_name': 'Результат прохождения теста',
                'verbose_name_plural': 'Результаты прохождения тестов',
                'ordering': ['owner', 'test'],
            },
        ),
        migrations.CreateModel(
            name='ResultScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Наименование шкалы')),
                ('scale_divisions_amount', models.IntegerField(default=0, verbose_name='Количество возможных оценок')),
                ('divisions_layout', models.CharField(help_text='Следует указать [количество возможных баллов/оценок - 1] элементов. Например, для 2-бальной шкалы (зачтено, незачтено) разметка делений может быть <q>50</q>', max_length=80, verbose_name='Разметка делений шкалы -- процентные доли каждого деления через запятую')),
            ],
            options={
                'verbose_name': 'Оценочная шкала',
                'verbose_name_plural': 'Оценочные шкалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Наименование тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_loader', models.BooleanField(default=False, verbose_name='Анонимный тест. На странице теста не будет указан пользователь, который загрузил тест.')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование теста')),
                ('description', models.TextField(default='Описание теста отсутствует...', verbose_name='Описание теста')),
                ('controlling', models.BooleanField(default=False, verbose_name='Использование контроля прохождения теста')),
                ('time_restricting', models.IntegerField(blank=True, null=True, verbose_name='Ограничение времени прохождения теста в минутах')),
                ('rating', models.IntegerField(default=0, editable=False, verbose_name='Рейтинг теста')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('ready_for_passing', models.BooleanField(default=False, editable=False, verbose_name='Готовность теста для прохождения другими пользователями')),
                ('show_answers', models.BooleanField(default=True, verbose_name='Показывать ответы после прохождения')),
                ('single_passing', models.BooleanField(default=False, verbose_name='Допускается пройти тест только один раз')),
                ('only_registered_can_pass', models.BooleanField(default=False, verbose_name='Только зарегистрированные и авторизованные пользователи могут проходить тест')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, загрузивший тест')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.Category', verbose_name='Категория теста')),
                ('result_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.ResultScale', verbose_name='Оценочная шкала теста')),
                ('tags', models.ManyToManyField(blank=True, related_name='tests', to='tests.Tag', verbose_name='Тег или теги теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(verbose_name='Тест понравился? Если True — +1 к рейтингу, иначе — -1 к рейтингу')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, к которому относится данная пользовательская оценка (рейтинг)')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='tests.Test', verbose_name='Тест, к которому относится данная пользовательская оценка (рейтинг)')),
            ],
            options={
                'verbose_name': 'Оценка тестов',
                'verbose_name_plural': 'Оценки тестов',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests.Test', verbose_name='Тест, к которому относится вопрос'),
        ),
    ]
