# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20171009_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_one_right', models.BooleanField(default=True, verbose_name='Только один вариант ответа — правильный.')),
                ('question_content', models.TextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) вопроса')),
                ('correct_option_numbers', models.CharField(help_text='Номера одного или нескольких правильных вариантов через запятую.', max_length=55, verbose_name='Правильны(й/е) вариант/варианты')),
            ],
            options={
                'verbose_name': 'Вопрос закрытого типа',
                'verbose_name_plural': 'Вопросы закрытого типа',
                'ordering': ['question_of_test'],
            },
        ),
        migrations.CreateModel(
            name='ClosedQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку. Не вводите пустые параграфы в качестве вариантов/элементов — такие варианты/элементы не будут добавлены. Также не будут добавлены варианты/последовательности, содержащие только пробелы.', verbose_name='Содержимое (контент) варианта ответа')),
                ('option_number', models.IntegerField(blank=True, help_text='Оставьте это поле пустым, чтобы добавить вариант вопроса последним (т.е. номер = кол-во вопросов + 1)', verbose_name='Порядковый номер варианта ответа на вопрос закр. типа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_options', to='tests.ClosedQuestion', verbose_name='Вопрос закрытого типа, которому принадлежит данный вариант ответа')),
            ],
            options={
                'verbose_name': 'Вариант ответа на вопрос закрытого типа',
                'verbose_name_plural': 'Варианты ответа на вопрос закрытого типа',
                'ordering': ['question', 'option_number'],
            },
        ),
        migrations.CreateModel(
            name='LevelOfTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_index_number', models.IntegerField(verbose_name='Порядковый номер уровня в тесте')),
                ('name_level', models.CharField(max_length=200, unique=True, verbose_name='Наименование уровня')),
                ('solution', models.TextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку. Не вводите пустые параграфы в качестве вариантов/элементов — такие варианты/элементы не будут добавлены. Также не будут добавлены варианты/последовательности, содержащие только пробелы.', verbose_name='Решение уровня')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels_of_test', to='tests.Test', verbose_name='Тест, к которому относится вопрос')),
            ],
            options={
                'verbose_name': 'Уровень теста',
                'verbose_name_plural': 'Уровни теста',
                'ordering': ['test'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOfTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index_number', models.IntegerField(verbose_name='Порядковый номер вопроса в тесте')),
                ('type_of_question', models.CharField(choices=[('ClsdQ', 'закрытый'), ('OpndQ', 'открытый'), ('SqncQ', 'последовательность'), ('CmprsnQ', 'сопоставление')], max_length=7, verbose_name='Тип теста, чтобы знать, к какому типу вопроса обращаться через связь')),
                ('level_of_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_of_question', to='tests.LevelOfTest', verbose_name='Уровень вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_of_test', to='tests.Test', verbose_name='Тест, к которому относится вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ['test'],
            },
        ),
        migrations.AddField(
            model_name='closedquestion',
            name='question_of_test',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_question', to='tests.QuestionOfTest', verbose_name='Нумерованный элемент (пункт) списка вопросов'),
        ),
    ]
